### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by kits-ragh** [PyCon/pycon-archive#1]
I want to use [Sourcegraph](https://sourcegraph.com) for pycon-archive code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/python/pycon-archive. (It should only take 30 seconds.)

Thank you!

**Comment by ewdurbin** [comment]
this repository is not intended for any source code. it is simply an archive of past pycon sites.
